creativescala/doodle

index.html
js/src/main/scala/doodle/js/Draw.scala
jvm/src/main/scala/doodle/jvm/Draw.scala
shared/src/main/scala/doodle/Example.scala
shared/src/main/scala/doodle/core/BoundingBox.scala
shared/src/main/scala/doodle/core/Image.scala
shared/src/main/scala/doodle/core/Point.scala
shared/src/main/scala/doodle/core/Vec.scala

Example
Circle(5) at (20, 20) on Circle(10)
This combinator allows you to layout an element at any position relative to
the local origin. This adds additional flexibility beyond what
on/above/beside offer, at the cost of more work for the user is
calculating layouts.
At layout also expands the bounding box to include the offset.

Add 'at' layout combinator

---

js/src/test/scala/doodle/core/AngleSpec.scala

Previously, running `sbt test` would introduce an error:
[error] /usr/local/google/home/namnguyen/tmp/doodle/js/src/test/scala/doodle/core/AngleSpec.scala:21: value get is not a member of Double
[error]         val converted = Angle.turns(original.toTurns.get)

Trivial fix to AngleSpec unit test

---

shared/src/main/scala/doodle/core/DrawingContext.scala

I've been enjoying the Creative Scala book a lot so far, but the pictures in the book didn't always match the pictures I was generating. I chalked it up to a platform-specific issue at first, but it bothered me enough at some point that I did some digging, and I'm pretty sure it's due to the stroke join being set to the [non-default](https://docs.oracle.com/javase/7/docs/api/java/awt/BasicStroke.html#BasicStroke%28float%29) "Bevel" type.
Example:
> (Triangle(100, 50) above Rectangle(80, 80) lineWidth 10).draw
Before change:
After change:

Changing default line join to be Miter rather than Bevel for sharp corners

---

.travis.yml
README.md
build.sbt
project/build.properties

Scala open source spree, Copenhagen, 2017

update versions and dates

---

js/src/main/scala/doodle/js/SvgCanvas.scala
jvm/src/main/scala/doodle/jvm/Java2DCanvas.scala
shared/src/main/scala/doodle/backend/Canvas.scala
shared/src/main/scala/doodle/backend/Finalised.scala
shared/src/main/scala/doodle/backend/Render.scala
shared/src/main/scala/doodle/core/Image.scala
shared/src/main/scala/doodle/examples/SandSpline.scala

`Image.draw` allows the user to provide a method that draws directly on the
canvas. This is generally faster than constructing an `Image` graph representing
an equivalent output and is the only way to render images with millions of
components. It is also arguably more suitable for certain types of output (e.g
images where there is little structure.)
Closes #43

Allow direct drawing on the Canvas

---

build.sbt

the cats part is needed now for Doodle to be included in the Scala
community build.  depending only on the parts of cats that are actually
needed is also generally good practice.
the ScalaCheck version bump isn't strictly necessary at the moment
but will help ensure community build compatibility moving forward.
the ScalaTest version bump is just for good measure.

tweak dependencies

---

js/src/main/scala/doodle/js/Svg.scala
js/src/main/scala/doodle/js/SvgCanvas.scala
js/src/main/scala/doodle/js/SvgFrame.scala
jvm/src/main/scala/doodle/jvm/Java2D.scala
jvm/src/main/scala/doodle/jvm/Java2DCanvas.scala
shared/src/main/scala/doodle/core/DrawingContext.scala
shared/src/main/scala/doodle/core/Gradient.scala
shared/src/main/scala/doodle/core/Image.scala
shared/src/main/scala/doodle/core/Style.scala
shared/src/main/scala/doodle/examples/GradientCircles.scala
shared/src/main/scala/doodle/examples/GradientSquares.scala

Hello. This PR brings gradient fill support for Doodle (issue #45). I did some research on the topic of gradient APIs in SVG and Java2D, and it turned out they are pretty much the same, except for the SVG allowing to choose between two coordinate systems (https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/gradientUnits), one of which (namely `userSpaceOnUse`) is compilant with Java2D coordinate system. Therefore, it was pretty straightforward to abstract the intersection of both worlds and implement it. The changes are not too invasive in `shared` nor `jvm`, but it required more changes in `js`. The reason for this is that SVG gradients need to be first defined in `<defs>` tag (preferably in the root `<svg>` element), and then referenced to by their ids. Therefore, I define the …

Gradient support

---

project/plugins.sbt

if this is merged, we'll no longer need to use a forked version
of doodle in the Scala community build

upgrade to dbuild-friendly version of sbt-bintray

---

build.sbt

We notice that the core package needs to be imported in order to run the example in the README file. 
(@renatocaval on behalf of @lucascaval)

import core package when launching console

---

build.sbt
project/build.properties

it's nbd, but merging the kind-projector org change would let me remove a
workaround from the Scala community build config.

version bumps

---

.travis.yml
svg/shared/src/main/scala/doodle/svg/effect/Svg.scala

Currently, JDK installation fails due to internal change in Travis.
This PR uses more robust way to install JDK when Travis update their base image.
This method (and AdoptOpenJDK) is commonly used in other Scala OSS  like https://github.com/scala/scala-collection-compat/pull/231
Also fixed the implementation to pass tests.

Fix broken CI

---

build.sbt
core/shared/src/main/scala/doodle/algebra/generic/reified/Reified.scala
image/jvm/src/main/scala/doodle/image/examples/Write.scala
java2d/src/main/scala/doodle/java2d/effect/Java2d.scala
java2d/src/main/scala/doodle/java2d/effect/Java2dWriter.scala
java2d/src/main/scala/doodle/java2d/package.scala

To do this a split up of the Java2d rendering was needed, to render a
Graphics2D context independent of a buffered image.
fixes https://github.com/creativescala/doodle/issues/46
+ fix some typos along the way

Add PDF writer based on https://github.com/eseifert/vectorgraphics2d

---

core/shared/src/main/scala/doodle/effect/Writer.scala
image/jvm/src/main/scala/doodle/image/examples/Write.scala
image/shared/src/main/scala/doodle/image/syntax/ImageSyntax.scala
java2d/src/main/scala/doodle/java2d/effect/Java2dWriter.scala
svg/jvm/src/main/scala/doodle/svg/effect/SvgWriter.scala

This extends the writer to return an image as base64 encoded
string (in the given format) instead of writing it to a file.
Currently it is only supported without the frame description.
fixes https://github.com/creativescala/doodle/issues/77

Allow to return a base64 encoded string for an image

---

interact/shared/src/main/scala/doodle/interact/animation/Transducer.scala

Transducer `repeatForever` will stop, when the parent transducer stops. 
Since it's repeating forever, it shouldn't stop.

Fix Repeat Forever

---

svg/shared/src/main/scala/doodle/svg/algebra/Svg.scala

Browsers and ebook readers will not render SVG tags properly if there is no XML namespace specified. This should also fix https://github.com/creativescala/creative-scala/issues/77 and https://github.com/creativescala/creative-scala/issues/72 once the images are re-rendered.

Add the XML namespace attribute when generating SVG tags

---

docs/src/pages/pictures/layout.md
image/shared/src/main/scala/doodle/image/Image.scala

Method works correctly and can take `Vec`, `Point`, x and y coordinates and polar coordinates just like the `originAt` in `Picture`.
Example with x, y coordinates:
```scala
val atAndOriginAt =
Image
.circle(100)
.at(25, 25)
.debug
.beside(Image.circle(100).originAt(25, 25).debug)
```
Output:
I've also updated the docs.

Added originAt support to Image

---

build.sbt
core/shared/src/main/scala/doodle/algebra/generic/package.scala
core/shared/src/test/scala/doodle/algebra/generic/LayoutSpec.scala
core/shared/src/test/scala/doodle/algebra/generic/TestAlgebra.scala
core/shared/src/test/scala/doodle/algebra/generic/reified/Reified.scala
golden/src/test/scala/doodle/golden/GoldenImage.scala
golden/src/test/scala/doodle/golden/GoldenPicture.scala
image/jvm/src/main/scala/doodle/image/syntax/JvmImageSyntax.scala
image/shared/src/main/scala-2.13/doodle/image/examples/Mandelbrot.scala
image/shared/src/main/scala/doodle/image/examples/GradientCircles.scala
image/shared/src/main/scala/doodle/image/examples/Koch.scala
image/shared/src/main/scala/doodle/image/examples/Layers.scala
image/shared/src/main/scala/doodle/image/examples/Layout.scala
image/shared/src/main/scala/doodle/image/examples/OpenClosedPaths.scala
image/shared/src/main/scala/doodle/image/examples/ParametricSamples.scala
image/shared/src/main/scala/doodle/image/examples/ParticleSystem.scala
image/shared/src/main/scala/doodle/image/examples/Polygon.scala
image/shared/src/main/scala/doodle/image/examples/RainbowSierpinski.scala
image/shared/src/main/scala/doodle/image/examples/Sierpinski.scala
image/shared/src/main/scala/doodle/image/examples/SierpinskiConfection.scala
image/shared/src/main/scala/doodle/image/examples/SierpinskiRipple.scala
image/shared/src/main/scala/doodle/image/examples/Sine.scala
image/shared/src/main/scala/doodle/image/examples/Smoke.scala
image/shared/src/main/scala/doodle/image/examples/Stars.scala
image/shared/src/main/scala/doodle/image/examples/Street.scala
image/shared/src/main/scala/doodle/image/examples/Tiles.scala
image/shared/src/main/scala/doodle/image/examples/Windswept.scala
image/shared/src/main/scala/doodle/image/syntax/AbstractImageSyntax.scala
java2d/src/main/scala/doodle/java2d/algebra/reified/Reified.scala

I was playing around with the Color class and noticed that my changes do not fail any tests. Apparently, the minitest suites were disabled in https://github.com/creativescala/doodle/commit/e9d3e46a4d15a456db3d03353d79f9b638ca1863. 
This change enables them again. I've also took upon fixing the build, which required removing redundant imports and loosening up on fatal warnings in the docs build.
Feel free to close if I do not have the full context and the tests are disabled by design.

Enable minitest and fix CI

---

build.sbt
core/jvm/src/main/scala/doodle/effect/BufferedImageConverter.scala
core/jvm/src/main/scala/doodle/syntax/BufferedImageConverterSyntax.scala
core/jvm/src/main/scala/doodle/syntax/package.scala
core/shared/src/main/scala/doodle/effect/BufferedImageConverter.scala
java2d/src/main/scala/doodle/java2d/effect/Java2dWriter.scala
java2d/src/main/scala/doodle/java2d/package.scala

Implement API for converting Picture to BufferedImage

---

.vscode/settings.json
core/jvm/src/main/scala/doodle/effect/BufferedImageWriter.scala
core/jvm/src/main/scala/doodle/syntax/Base64WriterSyntax.scala
core/jvm/src/main/scala/doodle/syntax/BufferedImageWriterSyntax.scala
core/jvm/src/main/scala/doodle/syntax/FileWriterSyntax.scala
core/jvm/src/main/scala/doodle/syntax/package.scala
core/shared/src/main/scala/doodle/effect/Base64Writer.scala
core/shared/src/main/scala/doodle/effect/FileWriter.scala
core/shared/src/main/scala/doodle/effect/Writer.scala
docs/src/pages/concepts/effects.md
docs/src/pages/effect/README.md
golden/src/test/scala/doodle/golden/GoldenPicture.scala
image/jvm/src/main/scala/doodle/image/syntax/JvmImageSyntax.scala
interact/shared/src/main/scala/doodle/interact/effect/AnimationWriter.scala
java2d/src/main/scala/doodle/java2d/effect/Java2d.scala
java2d/src/main/scala/doodle/java2d/effect/Java2dAnimationWriter.scala
java2d/src/main/scala/doodle/java2d/effect/Java2dBufferedImageWriter.scala
java2d/src/main/scala/doodle/java2d/effect/Java2dFileWriter.scala
java2d/src/main/scala/doodle/java2d/effect/Java2dWriter.scala
java2d/src/main/scala/doodle/java2d/package.scala
java2d/src/test/scala/doodle/java2d/Base64WriterSuite.scala
java2d/src/test/scala/doodle/java2d/FileWriterSuite.scala
java2d/src/test/scala/doodle/java2d/ToPictureSuite.scala
svg/jvm/src/main/scala/doodle/svg/effect/SvgWriter.scala
svg/jvm/src/main/scala/doodle/svg/package.scala

I renamed all "writing" effects to have a suffix `Writer`, updated sytax and moved `Java2dBuffereImageWriter` to a separate file. Additionally, I moved the `renderBufferedImage()` method from `Java2dWriter` to a `Java2d` as it is now used by multiple files. I decided not to proceed with creating a separate file to store all of the actuall writer objects as with the `renderBufferedImage()` method moved it seems to make more sense to leave them as they are (otherwise this file would become very large very quickly).
Closes #146

Add consistent naming of writers

---

svg/shared/src/main/scala/doodle/svg/algebra/Svg.scala
svg/shared/src/test/scala/doodle/svg/effect/SvgSpec.scala

There is a bug in SVG font rendering whereby monospace fonts are not recognised. 
[The MDN docs](https://developer.mozilla.org/en-US/docs/Web/CSS/font-family) specify that the family should be 'monospace', not 'monospaced'. 
Previous (monospaced):
Current (monospace):

Fixed Monospaced Fonts

---

canvas/src/main/scala/doodle/canvas/algebra/CanvasDrawing.scala

This PR implements gradient fill support in the Canvas backend, fixing #167.
- Added import for `doodle.core.Gradient`
- Implemented the `GradientFill` case in the `setFill` method
- Support for both linear and radial gradients using Canvas API's `createLinearGradient()` and `createRadialGradient()`
- Set inner radius to 0 for radial gradients to match expected behavior in other backends
- Verified gradient examples render correctly in the Canvas backend
- Tested in multiple browsers (Firefox, Chrome/Brave)
- Both linear and radial gradients display properly
This implementation preserves the existing code structure and formatting while adding the necessary functionality for gradient fills in Canvas.

Add Gradient Fill Support to Canvas Backend

---

algebra/js/src/main/scala/doodle/syntax/package.scala
algebra/jvm/src/main/scala/doodle/syntax/package.scala
algebra/shared/src/main/scala/doodle/algebra/BitmapError.scala
algebra/shared/src/main/scala/doodle/algebra/LoadBitmap.scala
algebra/shared/src/main/scala/doodle/syntax/LoadBitmapSyntax.scala
algebra/shared/src/test/scala/doodle/algebra/generic/LoadBitmapSpec.scala

Add LoadBitmap algebra for bitmap loading foundation:
- Add LoadBitmap trait for async bitmap loading.
- Define BitmapError hierarchy for type-safe error handling.
- Add LoadBitmapSyntax with IO-based extension methods.
- Add property-based tests for LoadBitmap.
This PR provides only the shared algebra and syntax. Platform-specific implementations and convenience methods will come in backend PRs.
Part of #85

Bitmap loading foundation

---

java2d/src/main/scala/doodle/java2d/algebra/Java2dLoadBitmap.scala
java2d/src/main/scala/doodle/java2d/package.scala
java2d/src/test/scala/doodle/java2d/Java2dLoadBitmapSuite.scala

- Implement LoadBitmap[File, BufferedImage]
- Implement LoadBitmap[Path, BufferedImage]
- Use Option pattern instead of null checks
- Add proper error mapping to typed errors
- Test suite
*Canvas, SVG implementation and convenience methods will be in the next PRs.*

Add LoadBitmap algebra implementation for Java2D backend

---

docs/src/pages/canvas/bitmap.md
docs/src/pages/canvas/directory.conf
docs/src/pages/svg/bitmap.md
docs/src/pages/svg/directory.conf
svg/js/src/main/scala/doodle/svg/algebra/Algebra.scala
svg/js/src/main/scala/doodle/svg/package.scala
svg/jvm/src/main/scala/doodle/svg/algebra/Algebra.scala
svg/jvm/src/main/scala/doodle/svg/package.scala
svg/shared/src/main/scala/doodle/svg/algebra/BaseAlgebra.scala
svg/shared/src/main/scala/doodle/svg/algebra/Image.scala
svg/shared/src/main/scala/doodle/svg/algebra/SvgLoadBitmap.scala
svg/shared/src/main/scala/doodle/svg/algebra/SvgToPicture.scala
svg/shared/src/test/scala/doodle/svg/SvgLoadBitmapSpec.scala
svg/shared/src/test/scala/doodle/svg/algebra/TestAlgebra.scala

SVG bitmap support differs from Canvas and Java2d bitmap refactoring task, because SVG doesn't manipulate pixels.  It references images via `<image>` elements with href attributes.
- `LoadBitmap[String, SvgImageRef] `- takes URL, returns image reference
- `ToPicture[SvgImageRef, Algebra]` - converts reference to `Picture` that generates `<image>` element
- package updates - add given instances to make it available
- tests - unit tests (SVG is cross-platform, so we can test in JVM environment)

Svg bitmap ref implementation, part of Bitmap refactoring task
